version: '3'

services:
  restrabbit:
    build: ./
    image: atareao/restrabbit
    container_name: restrabbit
    init: true
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - restrabbit.env
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external: true
